from abc import ABC, abstractmethod


class BlockchainConnector(ABC):
    """Abstract base class for blockchain connectors."""

    @abstractmethod
    def call_store_metrics(self, machine_id: str, payload: dict) -> str:
        """Call the Smart Contract for storing metrics for a specific machine.

        Args:
            machine_id (str): The ID of the machine to store metrics for.
            payload (dict): The JSON payload containing the metrics data.

        Returns:
            str: The transaction ID generated by invoking the Smart Contract.
        """
        pass

    @abstractmethod
    def call_aggregate_metrics(self, date_str: str) -> str:
        """Call the Smart Contract for aggregating metrics for a specific date.

        Args:
            date_str (str): The date string in the format "YYYY-MM-DD" to aggregate metrics for.

        Returns:
            str: The transaction ID generated by invoking the Smart Contract.
        """
        pass
